name: "Terraform Lambda"


on:
  push:
    branches: [ master ]


jobs:
  Terraform-Flow:
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        
    - name: Install Terraform
      env:
            TERRAFORM_VERSION: "0.15.1"
      run: |
        tf_version=$TERRAFORM_VERSION
        wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
        unzip terraform_"$tf_version"_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
        pip install boto3
        
    - name: Verify Terraform version
      run: terraform --version
      
    - name: Terraform fmt
      run: terraform fmt -recursive
      
    - name: Terraform init
      run: terraform init -input=false
    
    - name: Terraform validation
      run: terraform validate
      
    - name: Terraform plan
      run: terraform plan -var="env=test" -out tfplan -no-color
      
    - name: Terraform build
      run: terraform apply tfplan
    
    - name: Terraform test GET
      run: python ./test/test_get.py
        
    - name: Terraform test POST
      run: python ./test/test_post.py
        
    - name: Terraform clean
      run: terraform destroy -var="env=test" -auto-approve